### PR TITLE
Re cythonize

### PR DESCRIPTION
**Pull request by ocefpaf**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@maximlt, @rsignell-usgs, and @dbuscombe-usgs if you don't care for Windows now we can merge this one and work on fixing Windows later.

**Comment by rsignell-usgs** [comment]
@ocefpaf, this is awesome!   Do you think the Windows issues will be challenging to fix?

**Comment by ocefpaf** [comment]
> @ocefpaf, this is awesome! Do you think the Windows issues will be challenging to fix?

They are already fixed thanks to @maximlt.

**Comment by maximlt** [comment]
Amazing @ocefpaf you did some proper magic there!!! 🎉 Loving that thanks a lot!!! (btw I am not responsible for the Windows fix on pydensecrf, it's a contributor to the project).

**Comment by ocefpaf** [comment]
> I am not responsible for the Windows fix on pydensecrf, it's a contributor to the project

It takes a village, right? You are the one that showed me the right PR to make the patch :wink:

**Pull request merged**
